name: Encrypt Page

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  encrypt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install staticrypt
        run: sudo npm install -g staticrypt
      - name: Remove template salt (if necessary)
      # - name: Embed assets
      #   run: |
      #     pip3 install beautifulsoup4
      #     python3 embed.py
      - name: Encrypt indexgit status
        run: staticrypt main.html ${{ secrets.DECRYPTION_PASSPHRASE }} -f password_template.html -o index.html --title "Clairvoyant" --instructions "Jou geskenk lê hier binne, wat is die anwoord op die raaisel?" --decrypt-button "Wys my!" --embed true
        # run: staticrypt index.html ${{ secrets.DECRYPTION_PASSPHRASE }} -f password_template.html -o index.html --title "Clairvoyant" --instructions "Jou geskenk lê hier binne, wat is die anwoord op die raaisel?" --decrypt-button "Wys my!" --embed true
      - name: Commit files
        run: |
          git config --local user.name "Github Action"
          git add .
          git commit -m "encrypted files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
